//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 24.11.2015 11:52:59 by NFX.Templatization.TextCSTemplateCompiler at LAPTOP

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX; 
using NFX.Wave; 
using NFX.Wave.Templatization; 

namespace NewShortener.Pages 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public  class Index : NFX.Wave.Templatization.WaveTemplate
 {

     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Index._66_S_LITERAL_0 );
        Target.Write( Index._66_S_LITERAL_1 );

     }


     #region Literal blocks content
        private const string _66_S_LITERAL_0 = @"

"; 
        private const string _66_S_LITERAL_1 = @"
<!DOCTYPE html>

<html>
<head>
    <title>The shortener</title>
    <style>
        .text_inputs {
            width: 98%;
        }
    </style>

    <script type=""text/javascript"">
        function doAjax() {
            var xhr = new XMLHttpRequest();
            var txt = document.getElementById(""SrcLink"");
            xhr.open(""POST"", ""/newshortener/shorten?link="" + txt.value);
            xhr.setRequestHeader('Content-Type', 'text/plain');
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    processResponse(xhr.responseText);
                }
            }
            xhr.send();
        };

        function processResponse(res) {
            var res_a = document.getElementById(""result"");
            if (res == """")  {
                res_a.style.visibility = ""hidden"";
            }
            else {
                res_a.href = res;
                res_a.target = ""_blank"";
                res_a.innerHTML = res;
                res_a.style.visibility = ""visible"";
            }

        };
    </script>
</head>

<body>
    <form>
        <table width=""30%"" border=""0"">
            <tr>
                <td width=""5%""> Source:</td>
                <td width=""80%""> <input type=""text"" id=""SrcLink"" class=""text_inputs""> </td>
                <td> <button type=""button"" onclick=""doAjax()"" style=""width:98%""> Shorten</button> </td>
            </tr>
        </table>
        <br />
        <a id=""result"" style=""visibility:hidden""></a>
    </form>
</body>
</html>"; 
     #endregion

 }//class
}//namespace
